name: pb
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bullet-cpp=3.25=py312h5978115_5
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h38cb7af_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.8=hf598326_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsqlite=3.51.2=h1ae2325_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - ncurses=6.5=h5e97a16_3
  - numpy=2.4.1=py312he281c53_0
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pybullet=3.25=py312h3a599b7_5
  - python=3.12.12=h18782d2_1_cpython
  - python_abi=3.12=8_cp312
  - readline=8.3=h46df422_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_3
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libx11=1.8.12=h6a5fb8c_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xorg-libxext=1.3.6=hd74edd7_0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/pb
